#!/usr/bin/env bash
# SessionStart hook — Deterministically inject Session Start procedure on all startup/resume/clear/compact paths
#
# Official Specification (hooks-guide.md):
#   - matcher: startup / resume / clear / compact (trigger on all matchers)
#   - Plain text from stdout is injected into Claude's context as additionalContext
#   - Exit with status 0 on success. To avoid blocking the terminal on failure, do not use 'set -e' but gracefully degrade
#
# Purpose of this hook:
#   Obsoleted STEP 6.7 (inbox broadcast at startup) of depart.sh (commit 485ab9f, 2026-02-08)
#   Thereafter, Session Start was not triggered at startup, leaving the persona unestablished,
#   causing an incident where all agents misidentified themselves as the Shogun (2026-04-19).
#   The SessionStart hook deterministically injects the Session Start procedure, covering /clear and compaction as well.
#
# Note: Some specialist CLIs (Codex, etc.) are excluded from the Claude Code hook.
# This hook is triggered only in Claude Code sessions.
# In the Codex CLI environment, even if TMUX_PANE is set, @agent_id is not set,
# resulting in a silent exit and no logs being left (normal behavior).

set -uo pipefail

AGENT_ID=""
if [ -n "${TMUX_PANE:-}" ]; then
    AGENT_ID=$(tmux display-message -t "$TMUX_PANE" -p '#{@agent_id}' 2>/dev/null || true)
fi

# @agent_id not set (= individual Claude Code outside multi-agent environment) -> silent exit without interfering
if [ -z "$AGENT_ID" ]; then
    exit 0
fi

LOG_DIR="$(dirname "$0")/../logs"
mkdir -p "$LOG_DIR" || true
echo "[$(date -Iseconds)] $AGENT_ID session_start_hook fired" \
    >> "$LOG_DIR/session_start_hook.log" || true

case "$AGENT_ID" in
    shogun|orchestrator|oracle|council)
        # command/analysis-layer agents: full Session Start (Step 1-5)
        cat <<EOF
**CRITICAL: Execute Session Start procedure with the highest priority**

You are **${AGENT_ID}**. This is a verified fact read from the tmux pane; no guessing is required.

Execute the following in sequence (do not skip; user response and inbox processing will come after this):

1. Re-verify your identity using \`tmux display-message -t "\$TMUX_PANE" -p '#{@agent_id}'\`
2. Restore rules, preferences, and lessons using \`mcp__memory__read_graph\`
3. (Shogun only) Read \`memory/MEMORY.md\`
4. Read \`instructions/${AGENT_ID}.md\` to the end — re-establish your persona, Sengoku-style tone, and forbidden_actions **(ABSOLUTELY REQUIRED)**
5. Rebuild your state from the \`queue/\` directory (tasks/, inbox/, reports/)

**Inbox processing and user responses are FORBIDDEN until Steps 1-4 are completed**. Even if an inbox{N} nudge arrives first, ignore it and prioritize establishing your persona.

Rationale: There was a persona collapse incident on 2026-04-18 where an Orchestrator misidentified themselves as the Shogun.
Command/analysis-layer agents must re-establish their persona, Sengoku tone, and forbidden_actions.

Note: This message is automatically generated by the SessionStart hook (scripts/session_start_hook.sh)
by reading the @agent_id of the tmux pane, leaving no room for speculation or confusion.
EOF
        ;;
    explorer|librarian|designer|fixer|observer)
        # task-layer specialists: lightweight /clear Recovery procedure
        cat <<EOF
**CRITICAL: Execute Session Start procedure with the highest priority**

You are **${AGENT_ID}**. This is a verified fact read from the tmux pane.

Lightweight recovery procedure for specialist (in accordance with CLAUDE.md "/clear Recovery (specialist only)"):

1. Read \`queue/tasks/${AGENT_ID}.yaml\`
   - If status=assigned and work -> execute task
   - If idle -> wait
   - If done -> wait (DO NOT send report again)
2. If the task has a \`project:\` field -> Read \`context/{project}.md\`
3. If the task has a \`target_path:\` -> Read the target file
4. Begin work after completing Steps 1-3

**Inbox processing and user responses are FORBIDDEN until Steps 1-2 are completed**.
At initial startup, CLAUDE.md is automatically loaded; re-reading instructions/${AGENT_ID}.md is not required (cost saving).

This message is automatically generated by the SessionStart hook (scripts/session_start_hook.sh)
by reading the @agent_id of the tmux pane, leaving no room for speculation or confusion.
EOF
        ;;
    *)
        cat <<EOF
**Session Start**: agent_id=${AGENT_ID}. Follow the Session Start procedure in CLAUDE.md and read your own instructions/*.md.
EOF
        ;;
esac

# lint_lord_marker — Remind the Shogun to end the next reply with
# "### 📨 To Lord" if the captured pane has no marker in the recent history.
# This is a one-time nudge per check; the function can be called repeatedly
# (e.g. on every turn end) and will only fire when the marker is missing.
lint_lord_marker() {
    local target="${SHOGUN_TMUX_TARGET:-multiagent:0.0}"
    local pane
    pane="$(tmux capture-pane -t "$target" -p -S -500 2>/dev/null || true)"
    [[ -z "$pane" ]] && return 0

    # If zero markers in the recent pane, inject a reminder.
    local count
    count=$(printf '%s\n' "$pane" | grep -c "To Lord" || true)

    if [[ "$count" -eq 0 ]]; then
        tmux send-keys -t "$target" \
            "[system reminder] End your next reply with '### 📨 To Lord' block — Lord is reading via Telegram."
        sleep 0.3
        tmux send-keys -t "$target" "Enter"
    fi
}

# Fire the lint only when the Shogun is the one starting/resuming
if [[ "$AGENT_ID" == "shogun" ]]; then
    lint_lord_marker || true
fi

exit 0
